// Sound classification mapping for YAMNet to GIFs and display names
export interface SoundClassification {
  label: string;
  gif: any;
  displayName: string;
  category: 'emergency' | 'household' | 'nature' | 'music' | 'speech' | 'vehicle' | 'other' | 'animal' | 'mechanical' | 'electronic';
}

// Import GIFs using proper React Native syntax
const alarmGif = require('../assets/gifs/alarm.gif');
const doorbellGif = require('../assets/gifs/doorbell.gif');
const sirenGif = require('../assets/gifs/siren.gif');

// Default GIF for unknown sounds
const defaultGif = require('../assets/gifs/doorbell.gif');
export const DEFAULT_GIF = defaultGif; // exported fallback for other modules

export const soundClassificationMap: Record<string, SoundClassification> = {
  // Emergency sounds
  'Siren': { label: 'Siren', gif: sirenGif, displayName: 'Emergency Siren', category: 'emergency' },
  'Civil defense siren': { label: 'Civil defense siren', gif: sirenGif, displayName: 'Emergency Siren', category: 'emergency' },
  'Emergency vehicle': { label: 'Emergency vehicle', gif: sirenGif, displayName: 'Emergency Vehicle', category: 'emergency' },
  'Gunshot, gunfire': { label: 'Gunshot, gunfire', gif: alarmGif, displayName: 'Gunshot', category: 'emergency' },
  'Explosion': { label: 'Explosion', gif: alarmGif, displayName: 'Explosion', category: 'emergency' },
  'Fireworks': { label: 'Fireworks', gif: alarmGif, displayName: 'Fireworks', category: 'emergency' },
  'Alarm': { label: 'Alarm', gif: alarmGif, displayName: 'Alarm', category: 'emergency' },
  'Bell': { label: 'Bell', gif: doorbellGif, displayName: 'Bell', category: 'emergency' },
  'Police car (siren)': { label: 'Police car (siren)', gif: sirenGif, displayName: 'Police Siren', category: 'emergency' },
  'Fire engine, fire truck (siren)': { label: 'Fire engine, fire truck (siren)', gif: sirenGif, displayName: 'Fire Truck Siren', category: 'emergency' },
  'Ambulance (siren)': { label: 'Ambulance (siren)', gif: sirenGif, displayName: 'Ambulance Siren', category: 'emergency' },
  'Artillery fire': { label: 'Artillery fire', gif: alarmGif, displayName: 'Artillery Fire', category: 'emergency' },
  'Machine gun': { label: 'Machine gun', gif: alarmGif, displayName: 'Machine Gun', category: 'emergency' },
  'Fusillade': { label: 'Fusillade', gif: alarmGif, displayName: 'Fusillade', category: 'emergency' },
  'Cap gun': { label: 'Cap gun', gif: alarmGif, displayName: 'Cap Gun', category: 'emergency' },
  'Firecracker': { label: 'Firecracker', gif: alarmGif, displayName: 'Firecracker', category: 'emergency' },
  
  // Household sounds
  'Doorbell': { label: 'Doorbell', gif: doorbellGif, displayName: 'Doorbell', category: 'household' },
  'Computer keyboard': { label: 'Computer keyboard', gif: doorbellGif, displayName: 'Keyboard', category: 'household' },
  'Sink (filling or washing)': { label: 'Sink (filling or washing)', gif: doorbellGif, displayName: 'Sink', category: 'household' },
  'Frying (food)': { label: 'Frying (food)', gif: doorbellGif, displayName: 'Cooking', category: 'household' },
  'Tools': { label: 'Tools', gif: doorbellGif, displayName: 'Tools', category: 'household' },
  'Chainsaw': { label: 'Chainsaw', gif: doorbellGif, displayName: 'Chainsaw', category: 'household' },
  'Sawing': { label: 'Sawing', gif: doorbellGif, displayName: 'Sawing', category: 'household' },
  'Pump (liquid)': { label: 'Pump (liquid)', gif: doorbellGif, displayName: 'Pump', category: 'household' },
  'Vacuum cleaner': { label: 'Vacuum cleaner', gif: doorbellGif, displayName: 'Vacuum Cleaner', category: 'household' },
  'Sewing machine': { label: 'Sewing machine', gif: doorbellGif, displayName: 'Sewing Machine', category: 'household' },
  'Microwave oven': { label: 'Microwave oven', gif: doorbellGif, displayName: 'Microwave', category: 'household' },
  'Blender': { label: 'Blender', gif: doorbellGif, displayName: 'Blender', category: 'household' },
  'Printer': { label: 'Printer', gif: doorbellGif, displayName: 'Printer', category: 'household' },
  'Typewriter': { label: 'Typewriter', gif: doorbellGif, displayName: 'Typewriter', category: 'household' },
  'Typing': { label: 'Typing', gif: doorbellGif, displayName: 'Typing', category: 'household' },
  'Writing': { label: 'Writing', gif: doorbellGif, displayName: 'Writing', category: 'household' },
  'Camera': { label: 'Camera', gif: doorbellGif, displayName: 'Camera', category: 'household' },
  'Single-lens reflex camera': { label: 'Single-lens reflex camera', gif: doorbellGif, displayName: 'SLR Camera', category: 'household' },
  'Television': { label: 'Television', gif: doorbellGif, displayName: 'Television', category: 'household' },
  'Telephone': { label: 'Telephone', gif: doorbellGif, displayName: 'Telephone', category: 'household' },
  'Telephone bell ringing': { label: 'Telephone bell ringing', gif: doorbellGif, displayName: 'Phone Ringing', category: 'household' },
  'Telephone dialing, DTMF': { label: 'Telephone dialing, DTMF', gif: doorbellGif, displayName: 'Phone Dialing', category: 'household' },
  'Ringtone': { label: 'Ringtone', gif: doorbellGif, displayName: 'Ringtone', category: 'household' },
  'Dial tone': { label: 'Dial tone', gif: doorbellGif, displayName: 'Dial Tone', category: 'household' },
  'Busy signal': { label: 'Busy signal', gif: doorbellGif, displayName: 'Busy Signal', category: 'household' },
  'Sidetone': { label: 'Sidetone', gif: doorbellGif, displayName: 'Sidetone', category: 'household' },
  'Toilet flush': { label: 'Toilet flush', gif: doorbellGif, displayName: 'Toilet Flush', category: 'household' },
  'Bathtub (filling or washing)': { label: 'Bathtub (filling or washing)', gif: doorbellGif, displayName: 'Bathtub', category: 'household' },
  'Water tap, faucet': { label: 'Water tap, faucet', gif: doorbellGif, displayName: 'Water Tap', category: 'household' },
  'Dishes, pots, and pans': { label: 'Dishes, pots, and pans', gif: doorbellGif, displayName: 'Dishes', category: 'household' },
  'Cutlery, silverware': { label: 'Cutlery, silverware', gif: doorbellGif, displayName: 'Cutlery', category: 'household' },
  'Cupboard open or close': { label: 'Cupboard open or close', gif: doorbellGif, displayName: 'Cupboard', category: 'household' },
  'Drawer open or close': { label: 'Drawer open or close', gif: doorbellGif, displayName: 'Drawer', category: 'household' },
  'Door': { label: 'Door', gif: doorbellGif, displayName: 'Door', category: 'household' },
  'Sliding door': { label: 'Sliding door', gif: doorbellGif, displayName: 'Sliding Door', category: 'household' },
  'Knock': { label: 'Knock', gif: doorbellGif, displayName: 'Knock', category: 'household' },
  'Slam': { label: 'Slam', gif: doorbellGif, displayName: 'Slam', category: 'household' },
  'Clatter': { label: 'Clatter', gif: doorbellGif, displayName: 'Clatter', category: 'household' },
  'Clink, clink': { label: 'Clink, clink', gif: doorbellGif, displayName: 'Clink', category: 'household' },
  'Ding': { label: 'Ding', gif: doorbellGif, displayName: 'Ding', category: 'household' },
  'Ding-dong': { label: 'Ding-dong', gif: doorbellGif, displayName: 'Ding-dong', category: 'household' },
  'Toot': { label: 'Toot', gif: doorbellGif, displayName: 'Toot', category: 'household' },
  'Chime': { label: 'Chime', gif: doorbellGif, displayName: 'Chime', category: 'household' },
  'Shofar': { label: 'Shofar', gif: doorbellGif, displayName: 'Shofar', category: 'household' },
  'Cowbell': { label: 'Cowbell', gif: doorbellGif, displayName: 'Cowbell', category: 'household' },
  'Church bell': { label: 'Church bell', gif: doorbellGif, displayName: 'Church Bell', category: 'household' },
  'Change ringing (campanology)': { label: 'Change ringing (campanology)', gif: doorbellGif, displayName: 'Change Ringing', category: 'household' },
  'Clock': { label: 'Clock', gif: doorbellGif, displayName: 'Clock', category: 'household' },
  'Alarm clock': { label: 'Alarm clock', gif: doorbellGif, displayName: 'Alarm Clock', category: 'household' },
  'Car alarm': { label: 'Car alarm', gif: doorbellGif, displayName: 'Car Alarm', category: 'household' },
  'Fire alarm': { label: 'Fire alarm', gif: doorbellGif, displayName: 'Fire Alarm', category: 'household' },
  'Smoke detector, smoke alarm': { label: 'Smoke detector, smoke alarm', gif: doorbellGif, displayName: 'Smoke Alarm', category: 'household' },
  'Buzzer': { label: 'Buzzer', gif: doorbellGif, displayName: 'Buzzer', category: 'household' },
  'Air conditioning': { label: 'Air conditioning', gif: doorbellGif, displayName: 'Air Conditioning', category: 'household' },
  'Mechanical fan': { label: 'Mechanical fan', gif: doorbellGif, displayName: 'Fan', category: 'household' },
  'Hair dryer': { label: 'Hair dryer', gif: doorbellGif, displayName: 'Hair Dryer', category: 'household' },
  'Electric shaver, electric razor': { label: 'Electric shaver, electric razor', gif: doorbellGif, displayName: 'Electric Razor', category: 'household' },
  'Electric toothbrush': { label: 'Electric toothbrush', gif: doorbellGif, displayName: 'Electric Toothbrush', category: 'household' },
  'Toothbrush': { label: 'Toothbrush', gif: doorbellGif, displayName: 'Toothbrush', category: 'household' },
  'Lawn mower': { label: 'Lawn mower', gif: doorbellGif, displayName: 'Lawn Mower', category: 'household' },
  'Drill': { label: 'Drill', gif: doorbellGif, displayName: 'Drill', category: 'household' },
  'Jackhammer': { label: 'Jackhammer', gif: doorbellGif, displayName: 'Jackhammer', category: 'household' },
  'Power tool': { label: 'Power tool', gif: doorbellGif, displayName: 'Power Tool', category: 'household' },
  'Mechanisms': { label: 'Mechanisms', gif: doorbellGif, displayName: 'Mechanisms', category: 'household' },
  'Gears': { label: 'Gears', gif: doorbellGif, displayName: 'Gears', category: 'household' },
  'Pulleys': { label: 'Pulleys', gif: doorbellGif, displayName: 'Pulleys', category: 'household' },
  'Ratchet, pawl': { label: 'Ratchet, pawl', gif: doorbellGif, displayName: 'Ratchet', category: 'household' },
  'Cash register': { label: 'Cash register', gif: doorbellGif, displayName: 'Cash Register', category: 'household' },
  'Basketball bounce': { label: 'Basketball bounce', gif: doorbellGif, displayName: 'Basketball Bounce', category: 'household' },
  'Shuffling cards': { label: 'Shuffling cards', gif: doorbellGif, displayName: 'Card Shuffling', category: 'household' },
  'Zipper (clothing)': { label: 'Zipper (clothing)', gif: doorbellGif, displayName: 'Zipper', category: 'household' },
  'Scissors': { label: 'Scissors', gif: doorbellGif, displayName: 'Scissors', category: 'household' },
  'Hammer': { label: 'Hammer', gif: doorbellGif, displayName: 'Hammer', category: 'household' },
  'Filing (rasp)': { label: 'Filing (rasp)', gif: doorbellGif, displayName: 'Filing', category: 'household' },
  'Sanding': { label: 'Sanding', gif: doorbellGif, displayName: 'Sanding', category: 'household' },
  'Chopping (food)': { label: 'Chopping (food)', gif: doorbellGif, displayName: 'Chopping', category: 'household' },
  'Stir': { label: 'Stir', gif: doorbellGif, displayName: 'Stir', category: 'household' },
  'Pour': { label: 'Pour', gif: doorbellGif, displayName: 'Pour', category: 'household' },
  'Boiling': { label: 'Boiling', gif: doorbellGif, displayName: 'Boiling', category: 'household' },
  'Sizzle': { label: 'Sizzle', gif: doorbellGif, displayName: 'Sizzle', category: 'household' },
  'Chewing, mastication': { label: 'Chewing, mastication', gif: doorbellGif, displayName: 'Chewing', category: 'household' },
  'Biting': { label: 'Biting', gif: doorbellGif, displayName: 'Biting', category: 'household' },
  'Tearing': { label: 'Tearing', gif: doorbellGif, displayName: 'Tearing', category: 'household' },
  'Crumpling, crinkling': { label: 'Crumpling, crinkling', gif: doorbellGif, displayName: 'Crumpling', category: 'household' },
  'Crushing': { label: 'Crushing', gif: doorbellGif, displayName: 'Crushing', category: 'household' },
  'Splinter': { label: 'Splinter', gif: doorbellGif, displayName: 'Splinter', category: 'household' },
  'Breaking': { label: 'Breaking', gif: doorbellGif, displayName: 'Breaking', category: 'household' },
  'Shatter': { label: 'Shatter', gif: doorbellGif, displayName: 'Shatter', category: 'household' },
  'Smash, crash': { label: 'Smash, crash', gif: doorbellGif, displayName: 'Smash', category: 'household' },
  'Crack': { label: 'Crack', gif: doorbellGif, displayName: 'Crack', category: 'household' },
  'Crackle': { label: 'Crackle', gif: doorbellGif, displayName: 'Crackle', category: 'household' },
  'Creak': { label: 'Creak', gif: doorbellGif, displayName: 'Creak', category: 'household' },
  'Squeak': { label: 'Squeak', gif: doorbellGif, displayName: 'Squeak', category: 'household' },
  'Scratch': { label: 'Scratch', gif: doorbellGif, displayName: 'Scratch', category: 'household' },
  'Scratching (performance technique)': { label: 'Scratching (performance technique)', gif: doorbellGif, displayName: 'Scratching', category: 'household' },
  'Scrape': { label: 'Scrape', gif: doorbellGif, displayName: 'Scrape', category: 'household' },
  'Rub': { label: 'Rub', gif: doorbellGif, displayName: 'Rub', category: 'household' },
  'Tap': { label: 'Tap', gif: doorbellGif, displayName: 'Tap', category: 'household' },
  'Clicking': { label: 'Clicking', gif: doorbellGif, displayName: 'Clicking', category: 'household' },
  'Clickety-clack': { label: 'Clickety-clack', gif: doorbellGif, displayName: 'Clickety-clack', category: 'household' },
  'Ping': { label: 'Ping', gif: doorbellGif, displayName: 'Ping', category: 'household' },
  'Thunk': { label: 'Thunk', gif: doorbellGif, displayName: 'Thunk', category: 'household' },
  'Thump, thud': { label: 'Thump, thud', gif: doorbellGif, displayName: 'Thump', category: 'household' },
  'Boom': { label: 'Boom', gif: doorbellGif, displayName: 'Boom', category: 'household' },
  'Bang': { label: 'Bang', gif: doorbellGif, displayName: 'Bang', category: 'household' },
  'Slap, smack': { label: 'Slap, smack', gif: doorbellGif, displayName: 'Slap', category: 'household' },
  'Whip': { label: 'Whip', gif: doorbellGif, displayName: 'Whip', category: 'household' },
  'Chop': { label: 'Chop', gif: doorbellGif, displayName: 'Chop', category: 'household' },
  'Ice cream truck, ice cream van': { label: 'Ice cream truck, ice cream van', gif: doorbellGif, displayName: 'Ice Cream Truck', category: 'household' },
  
  // Nature sounds
  'Water': { label: 'Water', gif: doorbellGif, displayName: 'Water', category: 'nature' },
  'Wind': { label: 'Wind', gif: doorbellGif, displayName: 'Wind', category: 'nature' },
  'Stream': { label: 'Stream', gif: doorbellGif, displayName: 'Stream', category: 'nature' },
  'Outside, rural or natural': { label: 'Outside, rural or natural', gif: doorbellGif, displayName: 'Nature', category: 'nature' },
  'Traffic noise, roadway noise': { label: 'Traffic noise, roadway noise', gif: doorbellGif, displayName: 'Traffic', category: 'nature' },
  'Rustle': { label: 'Rustle', gif: doorbellGif, displayName: 'Rustling', category: 'nature' },
  'Rustling leaves': { label: 'Rustling leaves', gif: doorbellGif, displayName: 'Rustling Leaves', category: 'nature' },
  'Ocean': { label: 'Ocean', gif: doorbellGif, displayName: 'Ocean', category: 'nature' },
  'Waves, surf': { label: 'Waves, surf', gif: doorbellGif, displayName: 'Ocean Waves', category: 'nature' },
  'Waterfall': { label: 'Waterfall', gif: doorbellGif, displayName: 'Waterfall', category: 'nature' },
  'Rain': { label: 'Rain', gif: doorbellGif, displayName: 'Rain', category: 'nature' },
  'Rain on surface': { label: 'Rain on surface', gif: doorbellGif, displayName: 'Rain on Surface', category: 'nature' },
  'Raindrop': { label: 'Raindrop', gif: doorbellGif, displayName: 'Raindrop', category: 'nature' },
  'Thunder': { label: 'Thunder', gif: doorbellGif, displayName: 'Thunder', category: 'nature' },
  'Thunderstorm': { label: 'Thunderstorm', gif: doorbellGif, displayName: 'Thunderstorm', category: 'nature' },
  'Fire': { label: 'Fire', gif: doorbellGif, displayName: 'Fire', category: 'nature' },
  'Eruption': { label: 'Eruption', gif: doorbellGif, displayName: 'Eruption', category: 'nature' },
  'Inside, small room': { label: 'Inside, small room', gif: doorbellGif, displayName: 'Small Room', category: 'nature' },
  'Inside, large room or hall': { label: 'Inside, large room or hall', gif: doorbellGif, displayName: 'Large Room', category: 'nature' },
  'Inside, public space': { label: 'Inside, public space', gif: doorbellGif, displayName: 'Public Space', category: 'nature' },
  'Outside, urban or manmade': { label: 'Outside, urban or manmade', gif: doorbellGif, displayName: 'Urban Area', category: 'nature' },
  'Environmental noise': { label: 'Environmental noise', gif: doorbellGif, displayName: 'Environmental Noise', category: 'nature' },
  'Field recording': { label: 'Field recording', gif: doorbellGif, displayName: 'Field Recording', category: 'nature' },
  
  // Animal sounds
  'Animal': { label: 'Animal', gif: doorbellGif, displayName: 'Animal', category: 'nature' },
  'Dog': { label: 'Dog', gif: doorbellGif, displayName: 'Dog', category: 'nature' },
  'Cat': { label: 'Cat', gif: doorbellGif, displayName: 'Cat', category: 'nature' },
  'Bird': { label: 'Bird', gif: doorbellGif, displayName: 'Bird', category: 'nature' },
  'Bird vocalization, bird call, bird song': { label: 'Bird vocalization, bird call, bird song', gif: doorbellGif, displayName: 'Bird Song', category: 'nature' },
  'Fowl': { label: 'Fowl', gif: doorbellGif, displayName: 'Fowl', category: 'nature' },
  'Chirp, tweet': { label: 'Chirp, tweet', gif: doorbellGif, displayName: 'Bird Chirp', category: 'nature' },
  'Bark': { label: 'Bark', gif: doorbellGif, displayName: 'Dog Bark', category: 'nature' },
  'Meow': { label: 'Meow', gif: doorbellGif, displayName: 'Cat Meow', category: 'nature' },
  'Crow': { label: 'Crow', gif: doorbellGif, displayName: 'Crow', category: 'nature' },
  'Bleat': { label: 'Bleat', gif: doorbellGif, displayName: 'Sheep', category: 'nature' },
  'Oink': { label: 'Oink', gif: doorbellGif, displayName: 'Pig', category: 'nature' },
  'Cricket': { label: 'Cricket', gif: doorbellGif, displayName: 'Cricket', category: 'nature' },
  'Bee, wasp, etc.': { label: 'Bee, wasp, etc.', gif: doorbellGif, displayName: 'Bee', category: 'nature' },
  'Rodents, rats, mice': { label: 'Rodents, rats, mice', gif: doorbellGif, displayName: 'Rodents', category: 'nature' },
  'Pigeon, dove': { label: 'Pigeon, dove', gif: doorbellGif, displayName: 'Pigeon', category: 'animal' },
  'Chicken, rooster': { label: 'Chicken, rooster', gif: doorbellGif, displayName: 'Chicken', category: 'animal' },
  'Crowing, cock-a-doodle-doo': { label: 'Crowing, cock-a-doodle-doo', gif: doorbellGif, displayName: 'Rooster Crow', category: 'animal' },
  'Cluck': { label: 'Cluck', gif: doorbellGif, displayName: 'Chicken Cluck', category: 'animal' },
  'Duck': { label: 'Duck', gif: doorbellGif, displayName: 'Duck', category: 'animal' },
  'Quack': { label: 'Quack', gif: doorbellGif, displayName: 'Duck Quack', category: 'animal' },
  'Goose': { label: 'Goose', gif: doorbellGif, displayName: 'Goose', category: 'animal' },
  'Turkey': { label: 'Turkey', gif: doorbellGif, displayName: 'Turkey', category: 'animal' },
  'Gobble': { label: 'Gobble', gif: doorbellGif, displayName: 'Turkey Gobble', category: 'animal' },
  'Horse': { label: 'Horse', gif: doorbellGif, displayName: 'Horse', category: 'animal' },
  'Neigh, whinny': { label: 'Neigh, whinny', gif: doorbellGif, displayName: 'Horse Neigh', category: 'animal' },
  'Clip-clop': { label: 'Clip-clop', gif: doorbellGif, displayName: 'Horse Hooves', category: 'animal' },
  'Sheep': { label: 'Sheep', gif: doorbellGif, displayName: 'Sheep', category: 'animal' },
  'Cattle, bovinae': { label: 'Cattle, bovinae', gif: doorbellGif, displayName: 'Cattle', category: 'animal' },
  'Moo': { label: 'Moo', gif: doorbellGif, displayName: 'Cow Moo', category: 'animal' },
  'Bellow': { label: 'Bellow', gif: doorbellGif, displayName: 'Cow Bellow', category: 'animal' },
  'Goat': { label: 'Goat', gif: doorbellGif, displayName: 'Goat', category: 'animal' },
  'Pig': { label: 'Pig', gif: doorbellGif, displayName: 'Pig', category: 'animal' },
  'Frog': { label: 'Frog', gif: doorbellGif, displayName: 'Frog', category: 'animal' },
  'Croak': { label: 'Croak', gif: doorbellGif, displayName: 'Frog Croak', category: 'animal' },
  'Snake': { label: 'Snake', gif: doorbellGif, displayName: 'Snake', category: 'animal' },
  'Hiss': { label: 'Hiss', gif: doorbellGif, displayName: 'Snake Hiss', category: 'animal' },
  'Owl': { label: 'Owl', gif: doorbellGif, displayName: 'Owl', category: 'animal' },
  'Hoot': { label: 'Hoot', gif: doorbellGif, displayName: 'Owl Hoot', category: 'animal' },
  'Mouse': { label: 'Mouse', gif: doorbellGif, displayName: 'Mouse', category: 'animal' },
  'Squeal': { label: 'Squeal', gif: doorbellGif, displayName: 'Squeal', category: 'animal' },
  'Whale vocalization': { label: 'Whale vocalization', gif: doorbellGif, displayName: 'Whale', category: 'animal' },
  'Fly, housefly': { label: 'Fly, housefly', gif: doorbellGif, displayName: 'Fly', category: 'animal' },
  'Buzz': { label: 'Buzz', gif: doorbellGif, displayName: 'Buzz', category: 'animal' },
  'Mosquito': { label: 'Mosquito', gif: doorbellGif, displayName: 'Mosquito', category: 'animal' },
  'Wild animals': { label: 'Wild animals', gif: doorbellGif, displayName: 'Wild Animals', category: 'animal' },
  'Roaring cats (lions, tigers)': { label: 'Roaring cats (lions, tigers)', gif: doorbellGif, displayName: 'Big Cats', category: 'animal' },
  'Roar': { label: 'Roar', gif: doorbellGif, displayName: 'Roar', category: 'animal' },
  'Growling': { label: 'Growling', gif: doorbellGif, displayName: 'Growl', category: 'animal' },
  'Howl': { label: 'Howl', gif: doorbellGif, displayName: 'Howl', category: 'animal' },
  'Canidae, dogs, wolves': { label: 'Canidae, dogs, wolves', gif: doorbellGif, displayName: 'Canines', category: 'animal' },
  'Domestic animals, pets': { label: 'Domestic animals, pets', gif: doorbellGif, displayName: 'Pets', category: 'animal' },
  'Livestock, farm animals, working animals': { label: 'Livestock, farm animals, working animals', gif: doorbellGif, displayName: 'Farm Animals', category: 'animal' },
  
  // Vehicle sounds
  'Vehicle': { label: 'Vehicle', gif: doorbellGif, displayName: 'Vehicle', category: 'vehicle' },
  'Car': { label: 'Car', gif: doorbellGif, displayName: 'Car', category: 'vehicle' },
  'Motor vehicle (road)': { label: 'Motor vehicle (road)', gif: doorbellGif, displayName: 'Motor Vehicle', category: 'vehicle' },
  'Engine': { label: 'Engine', gif: doorbellGif, displayName: 'Engine', category: 'vehicle' },
  'Aircraft engine': { label: 'Aircraft engine', gif: doorbellGif, displayName: 'Aircraft', category: 'vehicle' },
  'Helicopter': { label: 'Helicopter', gif: doorbellGif, displayName: 'Helicopter', category: 'vehicle' },
  'Rail transport': { label: 'Rail transport', gif: doorbellGif, displayName: 'Train', category: 'vehicle' },
  'Railroad car, train wagon': { label: 'Railroad car, train wagon', gif: doorbellGif, displayName: 'Train', category: 'vehicle' },
  'Train horn': { label: 'Train horn', gif: doorbellGif, displayName: 'Train Horn', category: 'vehicle' },
  'Motorboat, speedboat': { label: 'Motorboat, speedboat', gif: doorbellGif, displayName: 'Boat', category: 'vehicle' },
  'Motorcycle': { label: 'Motorcycle', gif: doorbellGif, displayName: 'Motorcycle', category: 'vehicle' },
  'Truck': { label: 'Truck', gif: doorbellGif, displayName: 'Truck', category: 'vehicle' },
  'Bus': { label: 'Bus', gif: doorbellGif, displayName: 'Bus', category: 'vehicle' },
  'Race car, auto racing': { label: 'Race car, auto racing', gif: doorbellGif, displayName: 'Race Car', category: 'vehicle' },
  'Bicycle': { label: 'Bicycle', gif: doorbellGif, displayName: 'Bicycle', category: 'vehicle' },
  'Bicycle bell': { label: 'Bicycle bell', gif: doorbellGif, displayName: 'Bicycle Bell', category: 'vehicle' },
  'Ship': { label: 'Ship', gif: doorbellGif, displayName: 'Ship', category: 'vehicle' },
  'Sailboat, sailing ship': { label: 'Sailboat, sailing ship', gif: doorbellGif, displayName: 'Sailboat', category: 'vehicle' },
  'Rowboat, canoe, kayak': { label: 'Rowboat, canoe, kayak', gif: doorbellGif, displayName: 'Rowboat', category: 'vehicle' },
  'Boat, Water vehicle': { label: 'Boat, Water vehicle', gif: doorbellGif, displayName: 'Boat', category: 'vehicle' },
  'Subway, metro, underground': { label: 'Subway, metro, underground', gif: doorbellGif, displayName: 'Subway', category: 'vehicle' },
  'Train': { label: 'Train', gif: doorbellGif, displayName: 'Train', category: 'vehicle' },
  'Fixed-wing aircraft, airplane': { label: 'Fixed-wing aircraft, airplane', gif: doorbellGif, displayName: 'Airplane', category: 'vehicle' },
  'Aircraft': { label: 'Aircraft', gif: doorbellGif, displayName: 'Aircraft', category: 'vehicle' },
  'Jet engine': { label: 'Jet engine', gif: doorbellGif, displayName: 'Jet Engine', category: 'vehicle' },
  'Propeller, airscrew': { label: 'Propeller, airscrew', gif: doorbellGif, displayName: 'Propeller', category: 'vehicle' },
  'Skateboard': { label: 'Skateboard', gif: doorbellGif, displayName: 'Skateboard', category: 'vehicle' },
  'Vehicle horn, car horn, honking': { label: 'Vehicle horn, car horn, honking', gif: doorbellGif, displayName: 'Car Horn', category: 'vehicle' },
  'Air horn, truck horn': { label: 'Air horn, truck horn', gif: doorbellGif, displayName: 'Truck Horn', category: 'vehicle' },
  'Reversing beeps': { label: 'Reversing beeps', gif: doorbellGif, displayName: 'Reversing Beeps', category: 'vehicle' },
  'Train wheels squealing': { label: 'Train wheels squealing', gif: doorbellGif, displayName: 'Train Wheels', category: 'vehicle' },
  'Tire squeal': { label: 'Tire squeal', gif: doorbellGif, displayName: 'Tire Squeal', category: 'vehicle' },
  'Skidding': { label: 'Skidding', gif: doorbellGif, displayName: 'Skidding', category: 'vehicle' },
  'Car passing by': { label: 'Car passing by', gif: doorbellGif, displayName: 'Car Passing', category: 'vehicle' },
  'Accelerating, revving, vroom': { label: 'Accelerating, revving, vroom', gif: doorbellGif, displayName: 'Engine Revving', category: 'vehicle' },
  'Idling': { label: 'Idling', gif: doorbellGif, displayName: 'Engine Idling', category: 'vehicle' },
  'Engine starting': { label: 'Engine starting', gif: doorbellGif, displayName: 'Engine Starting', category: 'vehicle' },
  'Light engine (high frequency)': { label: 'Light engine (high frequency)', gif: doorbellGif, displayName: 'Light Engine', category: 'vehicle' },
  'Medium engine (mid frequency)': { label: 'Medium engine (mid frequency)', gif: doorbellGif, displayName: 'Medium Engine', category: 'vehicle' },
  'Heavy engine (low frequency)': { label: 'Heavy engine (low frequency)', gif: doorbellGif, displayName: 'Heavy Engine', category: 'vehicle' },
  
  // Music sounds
  'Music': { label: 'Music', gif: doorbellGif, displayName: 'Music', category: 'music' },
  'Musical instrument': { label: 'Musical instrument', gif: doorbellGif, displayName: 'Musical Instrument', category: 'music' },
  'Plucked string instrument': { label: 'Plucked string instrument', gif: doorbellGif, displayName: 'String Instrument', category: 'music' },
  'Singing': { label: 'Singing', gif: doorbellGif, displayName: 'Singing', category: 'music' },
  'Violin, fiddle': { label: 'Violin, fiddle', gif: doorbellGif, displayName: 'Violin', category: 'music' },
  'Drum': { label: 'Drum', gif: doorbellGif, displayName: 'Drum', category: 'music' },
  'Drum kit': { label: 'Drum kit', gif: doorbellGif, displayName: 'Drum Kit', category: 'music' },
  'Bass drum': { label: 'Bass drum', gif: doorbellGif, displayName: 'Bass Drum', category: 'music' },
  'Snare drum': { label: 'Snare drum', gif: doorbellGif, displayName: 'Snare Drum', category: 'music' },
  'Acoustic guitar': { label: 'Acoustic guitar', gif: doorbellGif, displayName: 'Acoustic Guitar', category: 'music' },
  'Double bass': { label: 'Double bass', gif: doorbellGif, displayName: 'Double Bass', category: 'music' },
  'Wind instrument, woodwind instrument': { label: 'Wind instrument, woodwind instrument', gif: doorbellGif, displayName: 'Wind Instrument', category: 'music' },
  'Brass instrument': { label: 'Brass instrument', gif: doorbellGif, displayName: 'Brass Instrument', category: 'music' },
  'Keyboard (musical)': { label: 'Keyboard (musical)', gif: doorbellGif, displayName: 'Musical Keyboard', category: 'music' },
  'Tambourine': { label: 'Tambourine', gif: doorbellGif, displayName: 'Tambourine', category: 'music' },
  'Tabla': { label: 'Tabla', gif: doorbellGif, displayName: 'Tabla', category: 'music' },
  'Hi-hat': { label: 'Hi-hat', gif: doorbellGif, displayName: 'Hi-hat', category: 'music' },
  'Choir': { label: 'Choir', gif: doorbellGif, displayName: 'Choir', category: 'music' },
  'Female singing': { label: 'Female singing', gif: doorbellGif, displayName: 'Female Singing', category: 'music' },
  'Rapping': { label: 'Rapping', gif: doorbellGif, displayName: 'Rapping', category: 'music' },
  'Male singing': { label: 'Male singing', gif: doorbellGif, displayName: 'Male Singing', category: 'music' },
  'Child singing': { label: 'Child singing', gif: doorbellGif, displayName: 'Child Singing', category: 'music' },
  'Synthetic singing': { label: 'Synthetic singing', gif: doorbellGif, displayName: 'Synthetic Singing', category: 'music' },
  'Yodeling': { label: 'Yodeling', gif: doorbellGif, displayName: 'Yodeling', category: 'music' },
  'Guitar': { label: 'Guitar', gif: doorbellGif, displayName: 'Guitar', category: 'music' },
  'Electric guitar': { label: 'Electric guitar', gif: doorbellGif, displayName: 'Electric Guitar', category: 'music' },
  'Steel guitar, slide guitar': { label: 'Steel guitar, slide guitar', gif: doorbellGif, displayName: 'Steel Guitar', category: 'music' },
  'Bass guitar': { label: 'Bass guitar', gif: doorbellGif, displayName: 'Bass Guitar', category: 'music' },
  'Banjo': { label: 'Banjo', gif: doorbellGif, displayName: 'Banjo', category: 'music' },
  'Mandolin': { label: 'Mandolin', gif: doorbellGif, displayName: 'Mandolin', category: 'music' },
  'Sitar': { label: 'Sitar', gif: doorbellGif, displayName: 'Sitar', category: 'music' },
  'Harp': { label: 'Harp', gif: doorbellGif, displayName: 'Harp', category: 'music' },
  'Ukulele': { label: 'Ukulele', gif: doorbellGif, displayName: 'Ukulele', category: 'music' },
  'Zither': { label: 'Zither', gif: doorbellGif, displayName: 'Zither', category: 'music' },
  'Strum': { label: 'Strum', gif: doorbellGif, displayName: 'Strum', category: 'music' },
  'Tapping (guitar technique)': { label: 'Tapping (guitar technique)', gif: doorbellGif, displayName: 'Guitar Tapping', category: 'music' },
  'Pizzicato': { label: 'Pizzicato', gif: doorbellGif, displayName: 'Pizzicato', category: 'music' },
  'Bowed string instrument': { label: 'Bowed string instrument', gif: doorbellGif, displayName: 'Bowed Strings', category: 'music' },
  'Cello': { label: 'Cello', gif: doorbellGif, displayName: 'Cello', category: 'music' },
  'Flute': { label: 'Flute', gif: doorbellGif, displayName: 'Flute', category: 'music' },
  'Clarinet': { label: 'Clarinet', gif: doorbellGif, displayName: 'Clarinet', category: 'music' },
  'Saxophone': { label: 'Saxophone', gif: doorbellGif, displayName: 'Saxophone', category: 'music' },
  'Trumpet': { label: 'Trumpet', gif: doorbellGif, displayName: 'Trumpet', category: 'music' },
  'Trombone': { label: 'Trombone', gif: doorbellGif, displayName: 'Trombone', category: 'music' },
  'French horn': { label: 'French horn', gif: doorbellGif, displayName: 'French Horn', category: 'music' },
  'Hammond organ': { label: 'Hammond organ', gif: doorbellGif, displayName: 'Hammond Organ', category: 'music' },
  'Electronic organ': { label: 'Electronic organ', gif: doorbellGif, displayName: 'Electronic Organ', category: 'music' },
  'Organ': { label: 'Organ', gif: doorbellGif, displayName: 'Organ', category: 'music' },
  'Piano': { label: 'Piano', gif: doorbellGif, displayName: 'Piano', category: 'music' },
  'Electric piano': { label: 'Electric piano', gif: doorbellGif, displayName: 'Electric Piano', category: 'music' },
  'Harpsichord': { label: 'Harpsichord', gif: doorbellGif, displayName: 'Harpsichord', category: 'music' },
  'Marimba, xylophone': { label: 'Marimba, xylophone', gif: doorbellGif, displayName: 'Marimba', category: 'music' },
  'Glockenspiel': { label: 'Glockenspiel', gif: doorbellGif, displayName: 'Glockenspiel', category: 'music' },
  'Vibraphone': { label: 'Vibraphone', gif: doorbellGif, displayName: 'Vibraphone', category: 'music' },
  'Steelpan': { label: 'Steelpan', gif: doorbellGif, displayName: 'Steelpan', category: 'music' },
  'Mallet percussion': { label: 'Mallet percussion', gif: doorbellGif, displayName: 'Mallet Percussion', category: 'music' },
  'Percussion': { label: 'Percussion', gif: doorbellGif, displayName: 'Percussion', category: 'music' },
  'Rimshot': { label: 'Rimshot', gif: doorbellGif, displayName: 'Rimshot', category: 'music' },
  'Drum roll': { label: 'Drum roll', gif: doorbellGif, displayName: 'Drum Roll', category: 'music' },
  'Wood block': { label: 'Wood block', gif: doorbellGif, displayName: 'Wood Block', category: 'music' },
  'Maraca': { label: 'Maraca', gif: doorbellGif, displayName: 'Maraca', category: 'music' },
  'Tubular bells': { label: 'Tubular bells', gif: doorbellGif, displayName: 'Tubular Bells', category: 'music' },
  'Gong': { label: 'Gong', gif: doorbellGif, displayName: 'Gong', category: 'music' },
  'Wind chime': { label: 'Wind chime', gif: doorbellGif, displayName: 'Wind Chime', category: 'music' },
  'Jingle bell': { label: 'Jingle bell', gif: doorbellGif, displayName: 'Jingle Bell', category: 'music' },
  'Tuning fork': { label: 'Tuning fork', gif: doorbellGif, displayName: 'Tuning Fork', category: 'music' },
  'Singing bowl': { label: 'Singing bowl', gif: doorbellGif, displayName: 'Singing Bowl', category: 'music' },
  'Theremin': { label: 'Theremin', gif: doorbellGif, displayName: 'Theremin', category: 'music' },
  'Sampler': { label: 'Sampler', gif: doorbellGif, displayName: 'Sampler', category: 'music' },
  'Synthesizer': { label: 'Synthesizer', gif: doorbellGif, displayName: 'Synthesizer', category: 'music' },
  'Effects unit': { label: 'Effects unit', gif: doorbellGif, displayName: 'Effects Unit', category: 'music' },
  'Drum machine': { label: 'Drum machine', gif: doorbellGif, displayName: 'Drum Machine', category: 'music' },
  'Electronic music': { label: 'Electronic music', gif: doorbellGif, displayName: 'Electronic Music', category: 'music' },
  'Dubstep': { label: 'Dubstep', gif: doorbellGif, displayName: 'Dubstep', category: 'music' },
  'Techno': { label: 'Techno', gif: doorbellGif, displayName: 'Techno', category: 'music' },
  'Rock and roll': { label: 'Rock and roll', gif: doorbellGif, displayName: 'Rock and Roll', category: 'music' },
  'Pop music': { label: 'Pop music', gif: doorbellGif, displayName: 'Pop Music', category: 'music' },
  'Rock music': { label: 'Rock music', gif: doorbellGif, displayName: 'Rock Music', category: 'music' },
  'Hip hop music': { label: 'Hip hop music', gif: doorbellGif, displayName: 'Hip Hop', category: 'music' },
  'Classical music': { label: 'Classical music', gif: doorbellGif, displayName: 'Classical Music', category: 'music' },
  'Soundtrack music': { label: 'Soundtrack music', gif: doorbellGif, displayName: 'Soundtrack', category: 'music' },
  'House music': { label: 'House music', gif: doorbellGif, displayName: 'House Music', category: 'music' },
  'Heavy metal': { label: 'Heavy metal', gif: doorbellGif, displayName: 'Heavy Metal', category: 'music' },
  'Exciting music': { label: 'Exciting music', gif: doorbellGif, displayName: 'Exciting Music', category: 'music' },
  'Country': { label: 'Country', gif: doorbellGif, displayName: 'Country Music', category: 'music' },
  'Electronica': { label: 'Electronica', gif: doorbellGif, displayName: 'Electronica', category: 'music' },
  'Rhythm and blues': { label: 'Rhythm and blues', gif: doorbellGif, displayName: 'R&B', category: 'music' },
  'Background music': { label: 'Background music', gif: doorbellGif, displayName: 'Background Music', category: 'music' },
  'Dance music': { label: 'Dance music', gif: doorbellGif, displayName: 'Dance Music', category: 'music' },
  'Jazz': { label: 'Jazz', gif: doorbellGif, displayName: 'Jazz', category: 'music' },
  'Mantra': { label: 'Mantra', gif: doorbellGif, displayName: 'Mantra', category: 'music' },
  'Blues': { label: 'Blues', gif: doorbellGif, displayName: 'Blues', category: 'music' },
  'Trance music': { label: 'Trance music', gif: doorbellGif, displayName: 'Trance', category: 'music' },
  'Electronic dance music': { label: 'Electronic dance music', gif: doorbellGif, displayName: 'EDM', category: 'music' },
  'Theme music': { label: 'Theme music', gif: doorbellGif, displayName: 'Theme Music', category: 'music' },
  'Gospel music': { label: 'Gospel music', gif: doorbellGif, displayName: 'Gospel', category: 'music' },
  'Music of Latin America': { label: 'Music of Latin America', gif: doorbellGif, displayName: 'Latin Music', category: 'music' },
  'Disco': { label: 'Disco', gif: doorbellGif, displayName: 'Disco', category: 'music' },
  'Tender music': { label: 'Tender music', gif: doorbellGif, displayName: 'Tender Music', category: 'music' },
  'Punk rock': { label: 'Punk rock', gif: doorbellGif, displayName: 'Punk Rock', category: 'music' },
  'Funk': { label: 'Funk', gif: doorbellGif, displayName: 'Funk', category: 'music' },
  'Music of Asia': { label: 'Music of Asia', gif: doorbellGif, displayName: 'Asian Music', category: 'music' },
  'Drum and bass': { label: 'Drum and bass', gif: doorbellGif, displayName: 'Drum and Bass', category: 'music' },
  'Vocal music': { label: 'Vocal music', gif: doorbellGif, displayName: 'Vocal Music', category: 'music' },
  'Progressive rock': { label: 'Progressive rock', gif: doorbellGif, displayName: 'Progressive Rock', category: 'music' },
  'Music for children': { label: 'Music for children', gif: doorbellGif, displayName: 'Children\'s Music', category: 'music' },
  'Video game music': { label: 'Video game music', gif: doorbellGif, displayName: 'Video Game Music', category: 'music' },
  'Lullaby': { label: 'Lullaby', gif: doorbellGif, displayName: 'Lullaby', category: 'music' },
  'Reggae': { label: 'Reggae', gif: doorbellGif, displayName: 'Reggae', category: 'music' },
  'New-age music': { label: 'New-age music', gif: doorbellGif, displayName: 'New Age', category: 'music' },
  'Christian music': { label: 'Christian music', gif: doorbellGif, displayName: 'Christian Music', category: 'music' },
  'Independent music': { label: 'Independent music', gif: doorbellGif, displayName: 'Indie Music', category: 'music' },
  'Soul music': { label: 'Soul music', gif: doorbellGif, displayName: 'Soul Music', category: 'music' },
  'Music of Africa': { label: 'Music of Africa', gif: doorbellGif, displayName: 'African Music', category: 'music' },
  'Ambient music': { label: 'Ambient music', gif: doorbellGif, displayName: 'Ambient Music', category: 'music' },
  'Bluegrass': { label: 'Bluegrass', gif: doorbellGif, displayName: 'Bluegrass', category: 'music' },
  'Afrobeat': { label: 'Afrobeat', gif: doorbellGif, displayName: 'Afrobeat', category: 'music' },
  'Salsa music': { label: 'Salsa music', gif: doorbellGif, displayName: 'Salsa', category: 'music' },
  'Music of Bollywood': { label: 'Music of Bollywood', gif: doorbellGif, displayName: 'Bollywood', category: 'music' },
  'Beatboxing': { label: 'Beatboxing', gif: doorbellGif, displayName: 'Beatboxing', category: 'music' },
  'Flamenco': { label: 'Flamenco', gif: doorbellGif, displayName: 'Flamenco', category: 'music' },
  'Psychedelic rock': { label: 'Psychedelic rock', gif: doorbellGif, displayName: 'Psychedelic Rock', category: 'music' },
  'Opera': { label: 'Opera', gif: doorbellGif, displayName: 'Opera', category: 'music' },
  'Folk music': { label: 'Folk music', gif: doorbellGif, displayName: 'Folk Music', category: 'music' },
  'Christmas music': { label: 'Christmas music', gif: doorbellGif, displayName: 'Christmas Music', category: 'music' },
  'Middle Eastern music': { label: 'Middle Eastern music', gif: doorbellGif, displayName: 'Middle Eastern Music', category: 'music' },
  'Grunge': { label: 'Grunge', gif: doorbellGif, displayName: 'Grunge', category: 'music' },
  'Song': { label: 'Song', gif: doorbellGif, displayName: 'Song', category: 'music' },
  'A capella': { label: 'A capella', gif: doorbellGif, displayName: 'A Capella', category: 'music' },
  'Sad music': { label: 'Sad music', gif: doorbellGif, displayName: 'Sad Music', category: 'music' },
  'Traditional music': { label: 'Traditional music', gif: doorbellGif, displayName: 'Traditional Music', category: 'music' },
  'Scary music': { label: 'Scary music', gif: doorbellGif, displayName: 'Scary Music', category: 'music' },
  'Ska': { label: 'Ska', gif: doorbellGif, displayName: 'Ska', category: 'music' },
  'Chant': { label: 'Chant', gif: doorbellGif, displayName: 'Chant', category: 'music' },
  'Carnatic music': { label: 'Carnatic music', gif: doorbellGif, displayName: 'Carnatic Music', category: 'music' },
  'Swing music': { label: 'Swing music', gif: doorbellGif, displayName: 'Swing Music', category: 'music' },
  'Happy music': { label: 'Happy music', gif: doorbellGif, displayName: 'Happy Music', category: 'music' },
  'Jingle (music)': { label: 'Jingle (music)', gif: doorbellGif, displayName: 'Jingle', category: 'music' },
  'Funny music': { label: 'Funny music', gif: doorbellGif, displayName: 'Funny Music', category: 'music' },
  'Angry music': { label: 'Angry music', gif: doorbellGif, displayName: 'Angry Music', category: 'music' },
  'Wedding music': { label: 'Wedding music', gif: doorbellGif, displayName: 'Wedding Music', category: 'music' },
  'Orchestra': { label: 'Orchestra', gif: doorbellGif, displayName: 'Orchestra', category: 'music' },
  'String section': { label: 'String section', gif: doorbellGif, displayName: 'String Section', category: 'music' },
  'Chorus effect': { label: 'Chorus effect', gif: doorbellGif, displayName: 'Chorus Effect', category: 'music' },
  'Harmonic': { label: 'Harmonic', gif: doorbellGif, displayName: 'Harmonic', category: 'music' },
  'Reverberation': { label: 'Reverberation', gif: doorbellGif, displayName: 'Reverb', category: 'music' },
  'Distortion': { label: 'Distortion', gif: doorbellGif, displayName: 'Distortion', category: 'music' },
  'Pulse': { label: 'Pulse', gif: doorbellGif, displayName: 'Pulse', category: 'music' },
  'Beat': { label: 'Beat', gif: doorbellGif, displayName: 'Beat', category: 'music' },
  
  // Speech sounds
  'Speech': { label: 'Speech', gif: alarmGif, displayName: 'Speech', category: 'speech' },
  'Narration, monologue': { label: 'Narration, monologue', gif: doorbellGif, displayName: 'Narration', category: 'speech' },
  'Child speech, kid speaking': { label: 'Child speech, kid speaking', gif: doorbellGif, displayName: 'Child Speech', category: 'speech' },
  'Female speech, woman speaking': { label: 'Female speech, woman speaking', gif: doorbellGif, displayName: 'Female Speech', category: 'speech' },
  'Male speech, man speaking': { label: 'Male speech, man speaking', gif: doorbellGif, displayName: 'Male Speech', category: 'speech' },
  'Laughter': { label: 'Laughter', gif: doorbellGif, displayName: 'Laughter', category: 'speech' },
  'Giggle': { label: 'Giggle', gif: doorbellGif, displayName: 'Giggle', category: 'speech' },
  'Cheering': { label: 'Cheering', gif: doorbellGif, displayName: 'Cheering', category: 'speech' },
  'Baby cry, infant cry': { label: 'Baby cry, infant cry', gif: doorbellGif, displayName: 'Baby Cry', category: 'speech' },
  'Snoring': { label: 'Snoring', gif: doorbellGif, displayName: 'Snoring', category: 'speech' },
  'Burping, eructation': { label: 'Burping, eructation', gif: doorbellGif, displayName: 'Burp', category: 'speech' },
  'Fart': { label: 'Fart', gif: doorbellGif, displayName: 'Fart', category: 'speech' },
  'Sneeze': { label: 'Sneeze', gif: doorbellGif, displayName: 'Sneeze', category: 'speech' },
  'Hiccup': { label: 'Hiccup', gif: doorbellGif, displayName: 'Hiccup', category: 'speech' },
  'Cough': { label: 'Cough', gif: doorbellGif, displayName: 'Cough', category: 'speech' },
  'Whispering': { label: 'Whispering', gif: doorbellGif, displayName: 'Whispering', category: 'speech' },
  'Crying, sobbing': { label: 'Crying, sobbing', gif: doorbellGif, displayName: 'Crying', category: 'speech' },
  'Screaming': { label: 'Screaming', gif: doorbellGif, displayName: 'Screaming', category: 'speech' },
  'Shout': { label: 'Shout', gif: doorbellGif, displayName: 'Shout', category: 'speech' },
  'Yell': { label: 'Yell', gif: doorbellGif, displayName: 'Yell', category: 'speech' },
  'Battle cry': { label: 'Battle cry', gif: doorbellGif, displayName: 'Battle Cry', category: 'speech' },
  'Chatter': { label: 'Chatter', gif: doorbellGif, displayName: 'Chatter', category: 'speech' },
  'Babbling': { label: 'Babbling', gif: doorbellGif, displayName: 'Babbling', category: 'speech' },
  'Conversation': { label: 'Conversation', gif: doorbellGif, displayName: 'Conversation', category: 'speech' },
  'Crowd': { label: 'Crowd', gif: doorbellGif, displayName: 'Crowd', category: 'speech' },
  'Hubbub, speech noise, speech babble': { label: 'Hubbub, speech noise, speech babble', gif: doorbellGif, displayName: 'Speech Noise', category: 'speech' },
  'Children shouting': { label: 'Children shouting', gif: doorbellGif, displayName: 'Children Shouting', category: 'speech' },
  'Children playing': { label: 'Children playing', gif: doorbellGif, displayName: 'Children Playing', category: 'speech' },
  'Applause': { label: 'Applause', gif: doorbellGif, displayName: 'Applause', category: 'speech' },
  'Clapping': { label: 'Clapping', gif: doorbellGif, displayName: 'Clapping', category: 'speech' },
  'Whimper': { label: 'Whimper', gif: doorbellGif, displayName: 'Whimper', category: 'speech' },
  'Whimper (dog)': { label: 'Whimper (dog)', gif: doorbellGif, displayName: 'Dog Whimper', category: 'speech' },
  'Snicker': { label: 'Snicker', gif: doorbellGif, displayName: 'Snicker', category: 'speech' },
  'Chuckle, chortle': { label: 'Chuckle, chortle', gif: doorbellGif, displayName: 'Chuckle', category: 'speech' },
  'Belly laugh': { label: 'Belly laugh', gif: doorbellGif, displayName: 'Belly Laugh', category: 'speech' },
  'Whoop': { label: 'Whoop', gif: doorbellGif, displayName: 'Whoop', category: 'speech' },
  'Throat clearing': { label: 'Throat clearing', gif: doorbellGif, displayName: 'Throat Clearing', category: 'speech' },
  'Sigh': { label: 'Sigh', gif: doorbellGif, displayName: 'Sigh', category: 'speech' },
  'Gasp': { label: 'Gasp', gif: doorbellGif, displayName: 'Gasp', category: 'speech' },
  'Humming': { label: 'Humming', gif: doorbellGif, displayName: 'Humming', category: 'speech' },
  'Whistling': { label: 'Whistling', gif: doorbellGif, displayName: 'Whistling', category: 'speech' },
  'Speech synthesizer': { label: 'Speech synthesizer', gif: doorbellGif, displayName: 'Speech Synthesizer', category: 'speech' },
  
  // Other sounds
  'Silence': { label: 'Silence', gif: doorbellGif, displayName: 'Silence', category: 'other' },
  'Tick': { label: 'Tick', gif: doorbellGif, displayName: 'Tick', category: 'other' },
  'Whack, thwack': { label: 'Whack, thwack', gif: doorbellGif, displayName: 'Whack', category: 'other' },
  'Arrow': { label: 'Arrow', gif: doorbellGif, displayName: 'Arrow', category: 'other' },
  'Radio': { label: 'Radio', gif: doorbellGif, displayName: 'Radio', category: 'other' },
  'Beep, bleep': { label: 'Beep, bleep', gif: doorbellGif, displayName: 'Beep', category: 'other' },
  'Liquid': { label: 'Liquid', gif: doorbellGif, displayName: 'Liquid', category: 'other' },
  'Steam': { label: 'Steam', gif: doorbellGif, displayName: 'Steam', category: 'other' },
  'Steam whistle': { label: 'Steam whistle', gif: doorbellGif, displayName: 'Steam Whistle', category: 'other' },
  'Foghorn': { label: 'Foghorn', gif: doorbellGif, displayName: 'Foghorn', category: 'other' },
  'Sonar': { label: 'Sonar', gif: doorbellGif, displayName: 'Sonar', category: 'other' },
  'Heart sounds, heartbeat': { label: 'Heart sounds, heartbeat', gif: doorbellGif, displayName: 'Heartbeat', category: 'other' },
  'Heart murmur': { label: 'Heart murmur', gif: doorbellGif, displayName: 'Heart Murmur', category: 'other' },
  'Stomach rumble': { label: 'Stomach rumble', gif: doorbellGif, displayName: 'Stomach Rumble', category: 'other' },
  'Breathing': { label: 'Breathing', gif: doorbellGif, displayName: 'Breathing', category: 'other' },
  'Pant': { label: 'Pant', gif: doorbellGif, displayName: 'Pant', category: 'other' },
  'Wheeze': { label: 'Wheeze', gif: doorbellGif, displayName: 'Wheeze', category: 'other' },
  'Groan': { label: 'Groan', gif: doorbellGif, displayName: 'Groan', category: 'other' },
  'Purr': { label: 'Purr', gif: doorbellGif, displayName: 'Purr', category: 'other' },
  'Rumble': { label: 'Rumble', gif: doorbellGif, displayName: 'Rumble', category: 'other' },
  'Boing': { label: 'Boing', gif: doorbellGif, displayName: 'Boing', category: 'other' },
  'Throbbing': { label: 'Throbbing', gif: doorbellGif, displayName: 'Throbbing', category: 'other' },
  'Vibration': { label: 'Vibration', gif: doorbellGif, displayName: 'Vibration', category: 'other' },
  'Wood': { label: 'Wood', gif: doorbellGif, displayName: 'Wood', category: 'other' },
  'Glass': { label: 'Glass', gif: doorbellGif, displayName: 'Glass', category: 'other' },
  'Coin (dropping)': { label: 'Coin (dropping)', gif: doorbellGif, displayName: 'Coin Drop', category: 'other' },
  'Keys jangling': { label: 'Keys jangling', gif: doorbellGif, displayName: 'Keys Jangling', category: 'other' },
  'Hands': { label: 'Hands', gif: doorbellGif, displayName: 'Hands', category: 'other' },
  'Finger snapping': { label: 'Finger snapping', gif: doorbellGif, displayName: 'Finger Snap', category: 'other' },
  'Gargling': { label: 'Gargling', gif: doorbellGif, displayName: 'Gargling', category: 'other' },
  'Noise': { label: 'Noise', gif: doorbellGif, displayName: 'Noise', category: 'other' },
  'White noise': { label: 'White noise', gif: doorbellGif, displayName: 'White Noise', category: 'other' },
  'Pink noise': { label: 'Pink noise', gif: doorbellGif, displayName: 'Pink Noise', category: 'other' },
  'Static': { label: 'Static', gif: doorbellGif, displayName: 'Static', category: 'other' },
  'Mains hum': { label: 'Mains hum', gif: doorbellGif, displayName: 'Mains Hum', category: 'other' },
  'Sine wave': { label: 'Sine wave', gif: doorbellGif, displayName: 'Sine Wave', category: 'other' },
  'Chirp tone': { label: 'Chirp tone', gif: doorbellGif, displayName: 'Chirp Tone', category: 'other' },
  'Sound effect': { label: 'Sound effect', gif: doorbellGif, displayName: 'Sound Effect', category: 'other' },
  'Cacophony': { label: 'Cacophony', gif: doorbellGif, displayName: 'Cacophony', category: 'other' },
  'Echo': { label: 'Echo', gif: doorbellGif, displayName: 'Echo', category: 'other' },
  'Wind noise (microphone)': { label: 'Wind noise (microphone)', gif: doorbellGif, displayName: 'Wind Noise', category: 'other' },
  'Run': { label: 'Run', gif: doorbellGif, displayName: 'Running', category: 'other' },
  'Walk, footsteps': { label: 'Walk, footsteps', gif: doorbellGif, displayName: 'Footsteps', category: 'other' },
  'Bouncing': { label: 'Bouncing', gif: doorbellGif, displayName: 'Bouncing', category: 'other' },
  'Trickle, dribble': { label: 'Trickle, dribble', gif: doorbellGif, displayName: 'Trickle', category: 'other' },
  'Splash, splatter': { label: 'Splash, splatter', gif: doorbellGif, displayName: 'Splash', category: 'other' },
  'Slosh': { label: 'Slosh', gif: doorbellGif, displayName: 'Slosh', category: 'other' },
  'Gush': { label: 'Gush', gif: doorbellGif, displayName: 'Gush', category: 'other' },
  'Plop': { label: 'Plop', gif: doorbellGif, displayName: 'Plop', category: 'other' },
  'Drip': { label: 'Drip', gif: doorbellGif, displayName: 'Drip', category: 'other' },
  'Whoosh, swoosh, swish': { label: 'Whoosh, swoosh, swish', gif: doorbellGif, displayName: 'Whoosh', category: 'other' },
  'Flap': { label: 'Flap', gif: doorbellGif, displayName: 'Flap', category: 'other' },
  'Bird flight, flapping wings': { label: 'Bird flight, flapping wings', gif: doorbellGif, displayName: 'Bird Flight', category: 'other' },
  'Engine knocking fix': { label: 'Engine knocking fix', gif: doorbellGif, displayName: 'Engine Fix', category: 'other' },
};

export function getSoundClassification(soundLabel: string): SoundClassification {
  // Normalize whatever the websocket sends:
  // - If JSON, try to extract a label-like field
  // - If verbose messages like "Received message: Detected: Speech", take last segment after colon
  // - Strip common prefixes like "Detected", "Sound", etc.
  let label = soundLabel || '';

  // Try parsing JSON payloads that may contain label info
  try {
    const t = label.trim();
    if (t.startsWith('{') || t.startsWith('[')) {
      const parsed = JSON.parse(t);
      // common fields
      label = parsed.label || parsed.sound || parsed.prediction || parsed.type || parsed.class || parsed[0] || label;
      if (typeof label !== 'string') label = String(label);
    }
  } catch {
    // ignore JSON parse errors
  }

  // If the string contains multiple colon-separated parts, use the last one
  if (label.indexOf(':') !== -1) {
    const parts = label.split(':');
    label = parts[parts.length - 1].trim();
  }

  // Remove common leading words e.g. "Detected", "Sound", "Label", etc.
  label = label.replace(/^(detected|sound|label|predicted|prediction)\s*[:\-\s]*/i, '').trim();

  // Try exact match first with normalized label
  if (label && soundClassificationMap[label]) {
    return soundClassificationMap[label];
  }

  // Fallback: try previous heuristics on the normalized label
  const lowerLabel = (label || '').toLowerCase();

  // Emergency-related
  if (lowerLabel.indexOf('siren') !== -1 || lowerLabel.indexOf('alarm') !== -1 || lowerLabel.indexOf('emergency') !== -1 || lowerLabel.indexOf('fire') !== -1 || lowerLabel.indexOf('gun') !== -1 || lowerLabel.indexOf('explosion') !== -1) {
    return soundClassificationMap['Siren'] || soundClassificationMap['Alarm'] || soundClassificationMap['Fire alarm'];
  }

  // Vehicle-related
  if (lowerLabel.indexOf('car') !== -1 || lowerLabel.indexOf('vehicle') !== -1 || lowerLabel.indexOf('engine') !== -1 || lowerLabel.indexOf('train') !== -1 || lowerLabel.indexOf('boat') !== -1 || lowerLabel.indexOf('aircraft') !== -1) {
    return soundClassificationMap['Car'] || soundClassificationMap['Vehicle'] || soundClassificationMap['Engine'];
  }

  // Animal-related
  if (lowerLabel.indexOf('dog') !== -1 || lowerLabel.indexOf('cat') !== -1 || lowerLabel.indexOf('bird') !== -1 || lowerLabel.indexOf('animal') !== -1 || lowerLabel.indexOf('rodent') !== -1 || lowerLabel.indexOf('horse') !== -1 || lowerLabel.indexOf('cow') !== -1) {
    return soundClassificationMap['Animal'] || soundClassificationMap['Dog'] || soundClassificationMap['Horse'];
  }

  // Music-related
  if (lowerLabel.indexOf('music') !== -1 || lowerLabel.indexOf('instrument') !== -1 || lowerLabel.indexOf('singing') !== -1 || lowerLabel.indexOf('guitar') !== -1 || lowerLabel.indexOf('drum') !== -1 || lowerLabel.indexOf('piano') !== -1) {
    return soundClassificationMap['Music'] || soundClassificationMap['Musical instrument'] || soundClassificationMap['Guitar'];
  }

  // Speech-related
  if (lowerLabel.indexOf('speech') !== -1 || lowerLabel.indexOf('speaking') !== -1 || lowerLabel.indexOf('voice') !== -1 || lowerLabel.indexOf('laugh') !== -1 || lowerLabel.indexOf('cry') !== -1) {
    return soundClassificationMap['Speech'] || soundClassificationMap['Narration, monologue'] || soundClassificationMap['Laughter'];
  }

  // Nature-related
  if (lowerLabel.indexOf('rustle') !== -1 || lowerLabel.indexOf('wind') !== -1 || lowerLabel.indexOf('water') !== -1 || lowerLabel.indexOf('rain') !== -1 || lowerLabel.indexOf('thunder') !== -1) {
    return soundClassificationMap['Rustle'] || soundClassificationMap['Wind'] || soundClassificationMap['Water'];
  }

  // Household/mechanical
  if (lowerLabel.indexOf('door') !== -1 || lowerLabel.indexOf('bell') !== -1 || lowerLabel.indexOf('clock') !== -1 || lowerLabel.indexOf('tool') !== -1 || lowerLabel.indexOf('machine') !== -1) {
    return soundClassificationMap['Doorbell'] || soundClassificationMap['Clock'] || soundClassificationMap['Tools'];
  }

  // Default fallback
  return {
    label: label || soundLabel,
    gif: defaultGif,
    displayName: label || soundLabel,
    category: 'other'
  };
}
